version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: telegrambot_api:latest
    ports:
      - "5000:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
  db:
    image: postgres:16
    container_name: telegramdb
    environment:
      - POSTGRES_USER=botuser
      - POSTGRES_PASSWORD=Abduvohid123!
      - POSTGRES_DB=telegrambotdb
    ports:
      - "5432:5432"
    restart: always
